
.DEFAULT: oled_sdcard_imgview.ice
ifdef tool
		silice-make.py -s oled_sdcard_imgview.ice -b $@ -p basic,oled,sdcard -o BUILD_$(subst :,_,$@) -t $(tool)
else
		silice-make.py -s oled_sdcard_imgview.ice -b $@ -p basic,oled,sdcard -o BUILD_$(subst :,_,$@)
endif

clean:
	rm -rf BUILD_*
