mch2022: write.si
	silice-make.py -s write.si -b $@ -p basic,uart,psram -o BUILD_$(subst :,_,$@) $(ARGS)

icebreaker: write.si
	silice-make.py -s write.si -b $@ -p basic,uart,pmod_qqspi -o BUILD_$(subst :,_,$@) $(ARGS)

icestick: write.si
	silice-make.py -s write.si -b $@ -p basic,uart,pmod_qqspi -o BUILD_$(subst :,_,$@) $(ARGS)

clean:
	rm -rf BUILD_*
