
.DEFAULT: video_bram_rv32i.ice
ifdef tool
		silice-make.py -s video_bram_rv32i.ice -b $@ -p basic,sdram,hdmi -o BUILD_$(subst :,_,$@) -t $(tool)
else
		silice-make.py -s video_bram_rv32i.ice -b $@ -p basic,sdram,hdmi -o BUILD_$(subst :,_,$@)
endif

verilator: video_bram_rv32i.ice
		silice-make.py -s video_bram_rv32i.ice -b $@ -p basic,sdram,vga -o BUILD_$(subst :,_,$@)

clean:
	rm -rf BUILD_*
