
.DEFAULT: blaze.ice
		silice-make.py -s blaze.ice -b $@ -p basic,sdcard -o BUILD_$(subst :,_,$@)

ulx3s: blaze.ice
		silice-make.py -s blaze.ice -b $@ -p basic,sdcard -o BUILD_$(subst :,_,$@) -t shell

verilator: blaze.ice
		silice-make.py -s blaze.ice -b $@ -p basic -o BUILD_$(subst :,_,$@) -t shell

clean:
	rm -rf BUILD_*
