
.DEFAULT: inferno.ice
		silice-make.py -s inferno.ice -b $@ -p basic,sdram,hdmi,sdcard,audio -o BUILD_$(subst :,_,$@) -t shell

verilator: inferno.ice
		silice-make.py -s inferno.ice -b $@ -p basic,vga,sdram -o BUILD_$(subst :,_,$@)

clean:
	rm -rf BUILD_*
