
.DEFAULT: spark.si
		silice-make.py -s spark.si -b $@ -p basic,sdcard -o BUILD_$(subst :,_,$@)

ulx3s: spark.si
		silice-make.py -s spark.si -b $@ -p basic,sdcard -o BUILD_$(subst :,_,$@) -t shell

icebreaker: spark.si
		silice-make.py -s spark.si -b $@ -p basic,spiflash -o BUILD_$(subst :,_,$@)

verilator: spark.si
		silice-make.py -s spark.si -b $@ -p basic -o BUILD_$(subst :,_,$@) -t shell

clean:
	rm -rf BUILD_*
