
.DEFAULT: testbench_rv32i.ice
		silice-make.py -s testbench_rv32i.ice -b $@ -p basic,sdcard -o BUILD_$(subst :,_,$@)

ulx3s: testbench_rv32i.ice
		silice-make.py -s testbench_rv32i.ice -b $@ -p basic,sdcard -o BUILD_$(subst :,_,$@) -t shell

verilator: testbench_rv32i.ice
		silice-make.py -s testbench_rv32i.ice -b $@ -p basic -o BUILD_$(subst :,_,$@) -t shell

clean:
	rm -rf BUILD_*
