
.DEFAULT: testbench_rv32i.ice
ifdef tool
		silice-make.py -s testbench_rv32i.ice -b $@ -p basic -o BUILD_$(subst :,_,$@) -t $(tool)
else
		silice-make.py -s testbench_rv32i.ice -b $@ -p basic -o BUILD_$(subst :,_,$@)
endif

clean:
	rm -rf BUILD_*
