
.DEFAULT: SOCs/ice-v-soc-ram.si
		silice-make.py -s SOCs/ice-v-soc-ram.si -b $@ -p basic,uart,pmod_qqspi,spiscreen_extra -o BUILD_$(subst :,_,$@) $(ARGS)

verilator: SOCs/ice-v-soc-ram.si
		silice-make.py -s SOCs/ice-v-soc-ram.si -b $@ -p basic,spiscreen -o BUILD_$(subst :,_,$@) $(ARGS)

stats: SOCs/ice-v-soc-ram.si
		silice-make.py -s SOCs/ice-v-soc-ram.si -b $@ -p basic,uart,pmod_qqspi,oled -o BUILD_$(subst :,_,$@) $(ARGS)

clean:
	rm -rf BUILD_*
