#line 2 "./src/VCDScanner.cpp"

#line 4 "./src/VCDScanner.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

/* %not-for-header */
/* %if-c-only */
/* %if-not-reentrant */
#define yy_create_buffer VCDParser_create_buffer
#define yy_delete_buffer VCDParser_delete_buffer
#define yy_scan_buffer VCDParser_scan_buffer
#define yy_scan_string VCDParser_scan_string
#define yy_scan_bytes VCDParser_scan_bytes
#define yy_init_buffer VCDParser_init_buffer
#define yy_flush_buffer VCDParser_flush_buffer
#define yy_load_buffer_state VCDParser_load_buffer_state
#define yy_switch_to_buffer VCDParser_switch_to_buffer
#define yypush_buffer_state VCDParserpush_buffer_state
#define yypop_buffer_state VCDParserpop_buffer_state
#define yyensure_buffer_stack VCDParserensure_buffer_stack
#define yy_flex_debug VCDParser_flex_debug
#define yyin VCDParserin
#define yyleng VCDParserleng
#define yylex VCDParserlex
#define yylineno VCDParserlineno
#define yyout VCDParserout
#define yyrestart VCDParserrestart
#define yytext VCDParsertext
#define yywrap VCDParserwrap
#define yyalloc VCDParseralloc
#define yyrealloc VCDParserrealloc
#define yyfree VCDParserfree

/* %endif */
/* %endif */
/* %ok-for-header */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* %if-c++-only */
/* %endif */

/* %if-c-only */
#ifdef yy_create_buffer
#define VCDParser_create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer VCDParser_create_buffer
#endif

#ifdef yy_delete_buffer
#define VCDParser_delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer VCDParser_delete_buffer
#endif

#ifdef yy_scan_buffer
#define VCDParser_scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer VCDParser_scan_buffer
#endif

#ifdef yy_scan_string
#define VCDParser_scan_string_ALREADY_DEFINED
#else
#define yy_scan_string VCDParser_scan_string
#endif

#ifdef yy_scan_bytes
#define VCDParser_scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes VCDParser_scan_bytes
#endif

#ifdef yy_init_buffer
#define VCDParser_init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer VCDParser_init_buffer
#endif

#ifdef yy_flush_buffer
#define VCDParser_flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer VCDParser_flush_buffer
#endif

#ifdef yy_load_buffer_state
#define VCDParser_load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state VCDParser_load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define VCDParser_switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer VCDParser_switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define VCDParserpush_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state VCDParserpush_buffer_state
#endif

#ifdef yypop_buffer_state
#define VCDParserpop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state VCDParserpop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define VCDParserensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack VCDParserensure_buffer_stack
#endif

#ifdef yylex
#define VCDParserlex_ALREADY_DEFINED
#else
#define yylex VCDParserlex
#endif

#ifdef yyrestart
#define VCDParserrestart_ALREADY_DEFINED
#else
#define yyrestart VCDParserrestart
#endif

#ifdef yylex_init
#define VCDParserlex_init_ALREADY_DEFINED
#else
#define yylex_init VCDParserlex_init
#endif

#ifdef yylex_init_extra
#define VCDParserlex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra VCDParserlex_init_extra
#endif

#ifdef yylex_destroy
#define VCDParserlex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy VCDParserlex_destroy
#endif

#ifdef yyget_debug
#define VCDParserget_debug_ALREADY_DEFINED
#else
#define yyget_debug VCDParserget_debug
#endif

#ifdef yyset_debug
#define VCDParserset_debug_ALREADY_DEFINED
#else
#define yyset_debug VCDParserset_debug
#endif

#ifdef yyget_extra
#define VCDParserget_extra_ALREADY_DEFINED
#else
#define yyget_extra VCDParserget_extra
#endif

#ifdef yyset_extra
#define VCDParserset_extra_ALREADY_DEFINED
#else
#define yyset_extra VCDParserset_extra
#endif

#ifdef yyget_in
#define VCDParserget_in_ALREADY_DEFINED
#else
#define yyget_in VCDParserget_in
#endif

#ifdef yyset_in
#define VCDParserset_in_ALREADY_DEFINED
#else
#define yyset_in VCDParserset_in
#endif

#ifdef yyget_out
#define VCDParserget_out_ALREADY_DEFINED
#else
#define yyget_out VCDParserget_out
#endif

#ifdef yyset_out
#define VCDParserset_out_ALREADY_DEFINED
#else
#define yyset_out VCDParserset_out
#endif

#ifdef yyget_leng
#define VCDParserget_leng_ALREADY_DEFINED
#else
#define yyget_leng VCDParserget_leng
#endif

#ifdef yyget_text
#define VCDParserget_text_ALREADY_DEFINED
#else
#define yyget_text VCDParserget_text
#endif

#ifdef yyget_lineno
#define VCDParserget_lineno_ALREADY_DEFINED
#else
#define yyget_lineno VCDParserget_lineno
#endif

#ifdef yyset_lineno
#define VCDParserset_lineno_ALREADY_DEFINED
#else
#define yyset_lineno VCDParserset_lineno
#endif

#ifdef yywrap
#define VCDParserwrap_ALREADY_DEFINED
#else
#define yywrap VCDParserwrap
#endif

/* %endif */

#ifdef yyalloc
#define VCDParseralloc_ALREADY_DEFINED
#else
#define yyalloc VCDParseralloc
#endif

#ifdef yyrealloc
#define VCDParserrealloc_ALREADY_DEFINED
#else
#define yyrealloc VCDParserrealloc
#endif

#ifdef yyfree
#define VCDParserfree_ALREADY_DEFINED
#else
#define yyfree VCDParserfree
#endif

/* %if-c-only */

#ifdef yytext
#define VCDParsertext_ALREADY_DEFINED
#else
#define yytext VCDParsertext
#endif

#ifdef yyleng
#define VCDParserleng_ALREADY_DEFINED
#else
#define yyleng VCDParserleng
#endif

#ifdef yyin
#define VCDParserin_ALREADY_DEFINED
#else
#define yyin VCDParserin
#endif

#ifdef yyout
#define VCDParserout_ALREADY_DEFINED
#else
#define yyout VCDParserout
#endif

#ifdef yy_flex_debug
#define VCDParser_flex_debug_ALREADY_DEFINED
#else
#define yy_flex_debug VCDParser_flex_debug
#endif

#ifdef yylineno
#define VCDParserlineno_ALREADY_DEFINED
#else
#define yylineno VCDParserlineno
#endif

/* %endif */

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
/* %if-c-only */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
/* %endif */

/* %if-tables-serialization */
/* %endif */
/* end standard C headers. */

/* %if-c-or-c++ */
/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* %endif */

/* begin standard C++ headers. */
/* %if-c++-only */
/* %endif */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* %not-for-header */
/* Returned upon end-of-file. */
#define YY_NULL 0
/* %ok-for-header */

/* %not-for-header */
/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))
/* %ok-for-header */

/* %if-reentrant */
/* %endif */

/* %if-not-reentrant */

/* %endif */

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

/* %if-not-reentrant */
extern int yyleng;
/* %endif */

/* %if-c-only */
/* %if-not-reentrant */
extern FILE *yyin, *yyout;
/* %endif */
/* %endif */

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
/* %if-c-only */
	FILE *yy_input_file;
/* %endif */

/* %if-c++-only */
/* %endif */

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */
/* %if-not-reentrant */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */
/* %endif */
/* %ok-for-header */

/* %endif */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* %if-c-only Standard (non-C++) definition */

/* %if-not-reentrant */
/* %not-for-header */
/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;
/* %ok-for-header */

/* %endif */

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

/* %endif */

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* %% [1.0] yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init go here */
/* Begin user sect3 */

#define VCDParserwrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

#define FLEX_DEBUG
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

/* %% [1.5] DFA */

/* %if-c-only Standard (non-C++) definition */

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* %endif */

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
/* %% [2.0] code to fiddle yytext and yyleng for yymore() goes here \ */\
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
/* %% [3.0] code to copy yytext_ptr to yytext[] goes here, if %array \ */\
	(yy_c_buf_p) = yy_cp;
/* %% [4.0] data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 61
#define YY_END_OF_BUFFER 62
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[243] =
    {   0,
        0,    0,    4,    4,    6,    6,    8,    8,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   62,   60,   57,   58,
       59,   47,   60,   53,   60,   60,    4,   60,    6,    8,
       10,   60,   60,   60,   60,   11,   60,   60,   60,   60,
       60,   60,   40,   60,   60,   60,   60,   60,   60,   60,
       60,   43,   41,   44,   45,   46,   48,   56,   56,    0,
        0,    0,    0,    0,    0,    0,   54,    0,    4,    0,
        6,    8,   10,   11,   18,   18,   18,   18,   18,   18,
       40,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,   42,   41,   44,   48,   56,   56,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   10,   18,
       18,   18,   18,   18,    0,    0,    0,    0,   27,    0,
        0,   31,    0,    0,   39,   56,    0,    0,    0,    1,
        0,    0,    0,   21,    0,    0,    2,   18,   14,   18,
       18,   17,    0,    0,    0,   25,    0,   30,   35,   36,
        0,    0,    0,   37,   38,    2,    0,    5,    0,    0,
        0,    0,    0,    0,   55,   55,   13,   18,   18,   22,
        0,    0,    0,    0,    0,   33,    0,    0,    0,    0,
        0,    0,   12,    0,    0,    0,   18,   16,    0,    0,

        0,    0,   32,   34,    0,    0,    0,   51,    0,    0,
        0,    0,    0,   18,   23,    0,    0,   28,   29,    3,
       49,   50,    0,    0,    0,   19,    7,   15,    0,   26,
       52,    0,    0,   24,    0,    9,    0,    0,    0,    0,
       20,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    5,    6,    7,    8,    5,    5,    5,    9,
        9,    5,   10,    5,   11,   10,    5,   12,   13,   14,
       14,   14,   14,   14,   14,   14,   15,   16,    5,    5,
        5,    5,    5,    5,   17,   18,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   19,   17,   20,
       21,    5,   22,    5,   17,    5,   23,   24,   25,   26,

       27,   28,   29,   17,   30,   17,   31,   32,   33,   34,
       35,   36,   17,   37,   38,   39,   40,   41,   42,   43,
       44,   45,    5,    5,    5,    5,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[46] =
    {   0,
        1,    1,    1,    1,    2,    3,    2,    3,    4,    2,
        2,    5,    5,    5,    5,    2,    5,    5,    5,    5,
        2,    2,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5
    } ;

static const flex_int16_t yy_base[257] =
    {   0,
        0,   44,    8,   17,   21,   25,   30,   52,   82,  115,
      155,    0,  193,    0,  235,  257,   68,   72,  272,  287,
       65,   70,   89,   96,  104,  123,  473,  474,  474,  474,
      474,  474,  285,  474,  262,  460,    0,  444,    0,    0,
      458,  431,  430,  429,  428,  474,  427,    0,  437,    0,
      428,  439,  120,  420,  426,  436,  431,  417,   12,   79,
        0,  474,    0,  124,  474,  474,  132,    0,  429,  420,
       27,  420,  428,  422,  415,    5,  277,  439,    0,  415,
        0,    0,  436,  474,    0,  418,  409,  411,  418,  405,
      197,  415,  402,  403,   30,  403,  405,  407,  402,  398,

      397,    0,    0,  201,  212,    0,  399,  399,  392,  397,
      403,  393,  394,  388,  388,  387,  408,  396,  474,  391,
      389,  394,  378,  386,  382,  388,  391,  381,  474,  376,
      384,  117,  384,  382,  474,  382,  374,  379,  369,  378,
      367,  375,  376,  474,  362,  304,  474,  365,    0,  359,
      365,    0,  357,  366,  361,  354,  360,  474,  474,  474,
      357,  353,  362,  474,  474,    0,  348,  474,   78,  347,
      343,  331,  330,  334,  474,  310,    0,  288,  290,  474,
      288,  281,  276,  260,  272,  474,  264,  258,  259,   60,
      260,  249,  474,  251,  219,  219,  218,    0,  215,  195,

      200,    9,  474,  474,  189,  190,  193,  474,  182,  188,
      194,  177,  169,  168,  474,  123,  115,  474,  474,  474,
      474,  474,  103,   87,   85,  474,  474,    0,   74,  474,
      474,   56,   39,  474,   26,  474,   25,   19,   10,    3,
      474,  474,  326,  331,  336,  341,  346,  351,  356,  361,
      366,  371,  373,  375,  379,  383
    } ;

static const flex_int16_t yy_def[257] =
    {   0,
      243,  243,  244,  244,  245,  245,  246,  246,  243,  243,
      242,   11,  243,   13,  247,  247,  248,  248,  243,  243,
      243,  243,    2,    2,  249,  249,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  250,  242,  251,  252,
      242,  242,  242,  242,  242,  242,  242,  253,  253,  253,
      253,  253,  242,  242,  242,  242,  242,  242,  242,  242,
      254,  242,  255,  242,  242,  242,  242,  256,  256,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  250,  242,
      251,  252,  242,  242,  253,  253,  253,  253,  253,  253,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,

      242,  254,  255,  242,  242,  256,  256,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  253,
      253,  253,  253,  253,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  256,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  253,  253,  253,
      253,  253,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  256,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  253,  253,  253,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  253,  253,  242,  242,

      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  253,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  253,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,    0,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242
    } ;

static const flex_int16_t yy_nxt[520] =
    {   0,
      242,   29,   30,   31,  242,  242,   32,   33,  242,  242,
      242,   34,   34,   28,  242,   38,   28,   35,   34,   34,
      218,  219,   28,   35,   38,   28,   28,  115,   38,   28,
       28,  116,   38,   28,   87,   28,   36,   38,   28,   88,
      241,   97,   34,  240,   34,   29,   30,   31,   98,  109,
       32,   33,  128,  239,  238,   34,   34,   28,  129,   38,
       28,   35,   34,   34,  237,  236,  110,   35,   28,   28,
       28,   28,   28,   28,   28,   28,   67,   67,   67,   67,
       36,   67,   67,   67,   67,  235,   34,  207,   34,   38,
       28,   28,   28,  208,   41,   28,   28,   28,   28,   28,

      189,   99,   28,   28,   28,   28,   28,   28,  100,   42,
      234,   69,  190,  101,   43,   44,  233,   45,  191,   46,
      232,   47,   38,   28,   28,   28,   28,   41,  159,  160,
       69,   91,   91,   91,   91,  104,  104,  104,  104,  161,
      231,  230,   42,  105,  105,  105,  105,   43,   44,  229,
       45,  162,   46,  163,   47,   28,   28,   28,   28,   28,
       28,   28,   38,   28,   28,   28,   28,   28,   28,   28,
       28,   48,   48,   48,   48,   28,   28,   48,   49,   48,
       48,   48,   50,   48,   48,   48,   48,   51,   48,   48,
       48,   48,   48,   52,   48,   48,   48,   48,   48,   48,

       38,  228,  227,  226,   53,   53,   53,   53,   91,   91,
       91,   91,  104,  104,  104,  104,  225,  224,  223,   54,
      222,  221,   55,  105,  105,  105,  105,  220,   56,   57,
       58,   59,  217,  216,   60,   28,   28,   28,   28,   28,
       28,   28,   38,   28,   28,   28,   28,   28,   28,   28,
       28,  215,  214,  213,  212,   62,   28,   28,   28,   28,
       28,   28,   28,   28,   38,   28,   28,   28,   28,   28,
       28,   28,   28,   77,   77,  211,  210,   62,   28,   38,
       77,   77,  209,   64,   64,   64,   64,   65,   77,   77,
      206,  205,  204,   66,   38,   77,   77,  203,   64,   64,

       64,   64,   65,  202,   77,  201,   77,  200,   66,   70,
       71,   72,  175,  175,  199,  176,  198,  197,  175,   77,
      117,   77,   73,   74,   75,   76,   28,   28,   28,   28,
       28,   37,   37,   37,   37,   37,   39,   39,   39,   39,
       39,   40,   40,   40,   40,   40,   61,   61,   61,   61,
       61,   63,   63,   63,   63,   63,   68,   68,   68,   68,
       68,   79,   79,  196,  195,   79,   81,   81,  194,  193,
       81,   82,   82,  192,  188,   82,   85,   85,  102,  102,
      103,  103,  103,  103,  106,  106,  106,  106,  187,  186,
      185,  184,  183,  182,  181,  180,  179,  178,  177,  174,

      173,  172,  171,  170,  169,  168,  167,  166,  165,  164,
      158,  157,  156,  155,  154,  153,  152,  151,  150,  149,
      148,  147,  146,  145,  144,  143,  142,  141,  140,  139,
      138,  137,  136,  135,  134,  133,  132,  131,  130,  127,
      126,  125,  124,  123,  122,  121,  120,  119,  118,  117,
      114,  113,  112,  111,  108,  107,   96,   95,   94,   93,
       92,   90,   89,   86,   84,   84,   84,   84,   84,   83,
       80,   78,  242,   27,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,

      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242
    } ;

static const flex_int16_t yy_chk[520] =
    {   0,
        0,    1,    1,    1,    0,    0,    1,    1,    0,    0,
        0,    1,    1,    3,    0,    3,    3,    1,    1,    1,
      202,  202,    4,    1,    4,    4,    5,   76,    5,    5,
        6,   76,    6,    6,   50,    7,    1,    7,    7,   50,
      240,   59,    1,  239,    1,    2,    2,    2,   59,   71,
        2,    2,   95,  238,  237,    2,    2,    8,   95,    8,
        8,    2,    2,    2,  235,  233,   71,    2,   17,   17,
       17,   17,   18,   18,   18,   18,   21,   21,   21,   21,
        2,   22,   22,   22,   22,  232,    2,  190,    2,    9,
       23,   23,   23,  190,    9,   23,   23,   24,   24,   24,

      169,   60,   24,   24,   25,   25,   25,   25,   60,    9,
      229,   25,  169,   60,    9,    9,  225,    9,  169,    9,
      224,    9,   10,   26,   26,   26,   26,   10,  132,  132,
       26,   53,   53,   53,   53,   64,   64,   64,   64,  132,
      223,  217,   10,   67,   67,   67,   67,   10,   10,  216,
       10,  132,   10,  132,   10,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,

       13,  214,  213,  212,   13,   13,   13,   13,   91,   91,
       91,   91,  104,  104,  104,  104,  211,  210,  209,   13,
      207,  206,   13,  105,  105,  105,  105,  205,   13,   13,
       13,   13,  201,  200,   13,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,  199,  197,  196,  195,   15,   15,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   35,   35,  194,  192,   16,   16,   19,
       35,   35,  191,   19,   19,   19,   19,   19,   77,   77,
      189,  188,  187,   19,   20,   77,   77,  185,   20,   20,

       20,   20,   20,  184,   35,  183,   35,  182,   20,   33,
       33,   33,  146,  146,  181,  146,  179,  178,  146,   77,
      176,   77,   33,   33,   33,   33,  243,  243,  243,  243,
      243,  244,  244,  244,  244,  244,  245,  245,  245,  245,
      245,  246,  246,  246,  246,  246,  247,  247,  247,  247,
      247,  248,  248,  248,  248,  248,  249,  249,  249,  249,
      249,  250,  250,  174,  173,  250,  251,  251,  172,  171,
      251,  252,  252,  170,  167,  252,  253,  253,  254,  254,
      255,  255,  255,  255,  256,  256,  256,  256,  163,  162,
      161,  157,  156,  155,  154,  153,  151,  150,  148,  145,

      143,  142,  141,  140,  139,  138,  137,  136,  134,  133,
      131,  130,  128,  127,  126,  125,  124,  123,  122,  121,
      120,  118,  117,  116,  115,  114,  113,  112,  111,  110,
      109,  108,  107,  101,  100,   99,   98,   97,   96,   94,
       93,   92,   90,   89,   88,   87,   86,   83,   80,   78,
       75,   74,   73,   72,   70,   69,   58,   57,   56,   55,
       54,   52,   51,   49,   47,   45,   44,   43,   42,   41,
       38,   36,   27,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,

      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 1;

static const flex_int16_t yy_rule_linenum[61] =
    {   0,
      108,  112,  117,  123,  128,  134,  139,  145,  150,  156,
      161,  181,  187,  192,  197,  202,  207,  212,  217,  222,
      227,  233,  234,  235,  236,  237,  238,  239,  240,  241,
      242,  243,  244,  245,  246,  247,  248,  249,  250,  252,
      258,  264,  269,  275,  280,  285,  290,  296,  302,  308,
      314,  320,  326,  355,  361,  367,  373,  374,  375,  382
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "./src/VCDScanner.l"
/*!
@file
@brief Contains the lexical definition for the parser.
*/
#line 7 "./src/VCDScanner.l"
    
#include <cerrno>
#include <climits>
#include <cstdlib>
#include <string>
#include <cstring>
#include <cstdio>

#include "VCDFileParser.hpp"
#include "VCDParser.hpp"

#undef yywrap
#define yywrap() 1

#define yyterminate() return VCDParser::parser::make_END(loc)

static VCDParser::location loc;
    
#line 1010 "./src/VCDScanner.cpp"
#define YY_NO_INPUT 1

#line 97 "./src/VCDScanner.l"
#define YY_USER_ACTION loc.columns(yyleng);
#line 1015 "./src/VCDScanner.cpp"
#line 1016 "./src/VCDScanner.cpp"

#define INITIAL 0
#define IN_COMMENT 1
#define IN_DATE 2
#define IN_VERSION 3
#define IN_TIMESCALE 4
#define IN_SCOPE 5
#define IN_VAR 6
#define IN_VAR_PID 7
#define IN_VAR_PSIZE 8
#define IN_VAR_RNG 9
#define IN_SIMTIME 10
#define IN_VAL_CHANGES 11
#define IN_VAL_IDCODE 12

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
/* %if-c-only */
#include <unistd.h>
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* %if-c-only Reentrant structure and macros (non-C++). */
/* %if-reentrant */
/* %if-c-only */

static int yy_init_globals ( void );

/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif End reentrant structures and macros. */

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* %if-bison-bridge */
/* %endif */

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

/* %not-for-header */
#ifndef YY_NO_UNPUT
    
#endif
/* %ok-for-header */

/* %endif */

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif
/* %ok-for-header */

/* %endif */
#endif

/* %if-c-only */

/* %endif */

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* %if-c-only Standard (non-C++) definition */
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
/* %% [5.0] fread()/read() definition of YY_INPUT goes here unless we're doing C++ \ */\
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\
/* %if-c++-only C++ definition \ */\
/* %endif */

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
/* %if-c-only */
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

/* %if-tables-serialization structures and prototypes */
/* %not-for-header */
/* %ok-for-header */

/* %not-for-header */
/* %tables-yydmap generated elements */
/* %endif */
/* end tables serialization structures and prototypes */

/* %ok-for-header */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
/* %if-c-only Standard (non-C++) definition */

extern int yylex (void);

#define YY_DECL int yylex (void)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

/* %% [6.0] YY_RULE_SETUP definition goes here */
#define YY_RULE_SETUP \
	YY_USER_ACTION

/* %not-for-header */
/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
/* %if-c-only */
			yyin = stdin;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! yyout )
/* %if-c-only */
			yyout = stdout;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
/* %% [7.0] user's declarations go here */
#line 100 "./src/VCDScanner.l"



#line 104 "./src/VCDScanner.l"
    loc.step();



#line 1315 "./src/VCDScanner.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
/* %% [8.0] yymore()-related code goes here */
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

/* %% [9.0] code to set up and find next match goes here */
		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 243 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 242 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
/* %% [10.0] code to find the action number goes here */
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

/* %% [11.0] code for yylineno update goes here */

do_action:	/* This label is used only to access EOF actions. */

/* %% [12.0] debug code goes here */
		if ( yy_flex_debug )
			{
			if ( yy_act == 0 )
				fprintf( stderr, "--scanner backing up\n" );
			else if ( yy_act < 61 )
				fprintf( stderr, "--accepting rule at line %ld (\"%s\")\n",
				         (long)yy_rule_linenum[yy_act], yytext );
			else if ( yy_act == 61 )
				fprintf( stderr, "--accepting default rule (\"%s\")\n",
				         yytext );
			else if ( yy_act == 62 )
				fprintf( stderr, "--(end of buffer or a NUL)\n" );
			else
				fprintf( stderr, "--EOF (start condition %d)\n", YY_START );
			}

		switch ( yy_act )
	{ /* beginning of action switch */
/* %% [13.0] actions go here */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 108 "./src/VCDScanner.l"
{
    return VCDParser::parser::make_TOK_KW_END(loc);
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 112 "./src/VCDScanner.l"
{
    BEGIN(INITIAL);
    return VCDParser::parser::make_TOK_KW_END(loc);
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 117 "./src/VCDScanner.l"
{
    BEGIN(IN_COMMENT);
    //std::cout << yytext << ", ";
    return VCDParser::parser::make_TOK_KW_COMMENT(loc);
}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 123 "./src/VCDScanner.l"
{
    //std::cout << yytext << ", ";
    return VCDParser::parser::make_TOK_COMMENT_TEXT(std::string(yytext),loc);
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 128 "./src/VCDScanner.l"
{
    BEGIN(IN_DATE);
    //std::cout << yytext << ", ";
    return VCDParser::parser::make_TOK_KW_DATE(loc);
}
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 134 "./src/VCDScanner.l"
{
    //std::cout << yytext << ", ";
    return VCDParser::parser::make_TOK_DATE_TEXT(std::string(yytext),loc);
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 139 "./src/VCDScanner.l"
{
    BEGIN(IN_VERSION);
    //std::cout << yytext << ", ";
    return VCDParser::parser::make_TOK_KW_VERSION(loc);
}
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 145 "./src/VCDScanner.l"
{
    //std::cout << yytext << ", ";
    return VCDParser::parser::make_TOK_VERSION_TEXT(std::string(yytext),loc);
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 150 "./src/VCDScanner.l"
{
    BEGIN(IN_TIMESCALE);
    //std::cout << yytext << ", ";
    return VCDParser::parser::make_TOK_KW_TIMESCALE(loc);
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 156 "./src/VCDScanner.l"
{
    //std::cout << yytext << ", ";
    return VCDParser::parser::make_TOK_TIME_NUMBER(std::atoi(yytext),loc);
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 161 "./src/VCDScanner.l"
{
    //std::cout << yytext << ", ";
    VCDTimeUnit tr = TIME_S;

    if(std::strcmp(yytext, "s")) {
        tr = TIME_S;
    } else if(std::strcmp(yytext, "ms")) {
        tr = TIME_MS;
    } else if(std::strcmp(yytext, "us")) {
        tr = TIME_US;
    } else if(std::strcmp(yytext, "ns")) {
        tr = TIME_NS;
    } else if(std::strcmp(yytext, "ps")) {
        tr = TIME_PS;
    }

    return VCDParser::parser::make_TOK_TIME_UNIT(tr,loc);
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 181 "./src/VCDScanner.l"
{
    BEGIN(IN_SCOPE);
    //std::cout << yytext << ", ";
    return VCDParser::parser::make_TOK_KW_SCOPE(loc);
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 187 "./src/VCDScanner.l"
{
    //std::cout << yytext << ", ";
    return VCDParser::parser::make_TOK_KW_BEGIN(VCD_SCOPE_BEGIN,loc);
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 192 "./src/VCDScanner.l"
{
    //std::cout << yytext << ", ";
    return VCDParser::parser::make_TOK_KW_FORK(VCD_SCOPE_FORK,loc);
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 197 "./src/VCDScanner.l"
{
    //std::cout << yytext << ", ";
    return VCDParser::parser::make_TOK_KW_FUNCTION(VCD_SCOPE_FUNCTION, loc);
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 202 "./src/VCDScanner.l"
{
    //std::cout << yytext << ", ";
    return VCDParser::parser::make_TOK_KW_MODULE(VCD_SCOPE_MODULE, loc);
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 207 "./src/VCDScanner.l"
{
    //std::cout << yytext << ", ";
    return VCDParser::parser::make_TOK_KW_TASK(VCD_SCOPE_TASK, loc);
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 212 "./src/VCDScanner.l"
{
    //std::cout << yytext << ", ";
    return VCDParser::parser::make_TOK_IDENTIFIER(std::string(yytext),loc);
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 217 "./src/VCDScanner.l"
{
    //std::cout << yytext << ", ";
    return VCDParser::parser::make_TOK_KW_UPSCOPE(loc);
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 222 "./src/VCDScanner.l"
{
    //std::cout << yytext << ", ";
    return VCDParser::parser::make_TOK_KW_ENDDEFINITIONS(loc);
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 227 "./src/VCDScanner.l"
{
    BEGIN(IN_VAR);
    //std::cout << yytext << ", ";
    return VCDParser::parser::make_TOK_KW_VAR(loc);
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 233 "./src/VCDScanner.l"
{return VCDParser::parser::make_TOK_VAR_TYPE(VCD_VAR_EVENT    ,loc);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 234 "./src/VCDScanner.l"
{return VCDParser::parser::make_TOK_VAR_TYPE(VCD_VAR_INTEGER  ,loc);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 235 "./src/VCDScanner.l"
{return VCDParser::parser::make_TOK_VAR_TYPE(VCD_VAR_PARAMETER,loc);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 236 "./src/VCDScanner.l"
{return VCDParser::parser::make_TOK_VAR_TYPE(VCD_VAR_REAL     ,loc);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 237 "./src/VCDScanner.l"
{return VCDParser::parser::make_TOK_VAR_TYPE(VCD_VAR_REALTIME ,loc);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 238 "./src/VCDScanner.l"
{return VCDParser::parser::make_TOK_VAR_TYPE(VCD_VAR_REG      ,loc);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 239 "./src/VCDScanner.l"
{return VCDParser::parser::make_TOK_VAR_TYPE(VCD_VAR_SUPPLY0  ,loc);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 240 "./src/VCDScanner.l"
{return VCDParser::parser::make_TOK_VAR_TYPE(VCD_VAR_SUPPLY1  ,loc);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 241 "./src/VCDScanner.l"
{return VCDParser::parser::make_TOK_VAR_TYPE(VCD_VAR_TIME     ,loc);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 242 "./src/VCDScanner.l"
{return VCDParser::parser::make_TOK_VAR_TYPE(VCD_VAR_TRI      ,loc);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 243 "./src/VCDScanner.l"
{return VCDParser::parser::make_TOK_VAR_TYPE(VCD_VAR_TRIAND   ,loc);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 244 "./src/VCDScanner.l"
{return VCDParser::parser::make_TOK_VAR_TYPE(VCD_VAR_TRIOR    ,loc);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 245 "./src/VCDScanner.l"
{return VCDParser::parser::make_TOK_VAR_TYPE(VCD_VAR_TRIREG   ,loc);}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 246 "./src/VCDScanner.l"
{return VCDParser::parser::make_TOK_VAR_TYPE(VCD_VAR_TRI0     ,loc);}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 247 "./src/VCDScanner.l"
{return VCDParser::parser::make_TOK_VAR_TYPE(VCD_VAR_TRI1     ,loc);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 248 "./src/VCDScanner.l"
{return VCDParser::parser::make_TOK_VAR_TYPE(VCD_VAR_WAND     ,loc);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 249 "./src/VCDScanner.l"
{return VCDParser::parser::make_TOK_VAR_TYPE(VCD_VAR_WIRE     ,loc);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 250 "./src/VCDScanner.l"
{return VCDParser::parser::make_TOK_VAR_TYPE(VCD_VAR_WOR      ,loc);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 252 "./src/VCDScanner.l"
{
    BEGIN(IN_VAR_PSIZE);
    //std::cout << yytext << ", ";
    return VCDParser::parser::make_TOK_DECIMAL_NUM(std::atoi(yytext),loc);
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 258 "./src/VCDScanner.l"
{
    BEGIN(IN_VAR_PID);
    //std::cout << yytext << ", ";
    return VCDParser::parser::make_TOK_IDENTIFIER(std::string(yytext),loc);
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 264 "./src/VCDScanner.l"
{
    //std::cout << yytext << ", ";
    return VCDParser::parser::make_TOK_IDENTIFIER(std::string(yytext),loc);
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 269 "./src/VCDScanner.l"
{
    BEGIN(IN_VAR_RNG);
    //std::cout << yytext << ", ";
    return VCDParser::parser::make_TOK_BRACKET_O(loc);
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 275 "./src/VCDScanner.l"
{
    //std::cout << yytext << ", ";
    return VCDParser::parser::make_TOK_DECIMAL_NUM(std::atoi(yytext),loc);
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 280 "./src/VCDScanner.l"
{
    //std::cout << yytext << ", ";
    return VCDParser::parser::make_TOK_COLON(loc);
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 285 "./src/VCDScanner.l"
{
    //std::cout << yytext << ", ";
    return VCDParser::parser::make_TOK_BRACKET_C(loc);
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 290 "./src/VCDScanner.l"
{
    BEGIN(IN_SIMTIME);
    //std::cout << "simtime: " << yytext << ", ";
    return VCDParser::parser::make_TOK_HASH(loc);
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 296 "./src/VCDScanner.l"
{
    BEGIN(INITIAL);
    //std::cout << yytext << std::endl;
    return VCDParser::parser::make_TOK_DECIMAL_NUM(std::atoi(yytext),loc);
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 302 "./src/VCDScanner.l"
{
    BEGIN(IN_VAL_CHANGES);
    //std::cout << yytext << ", ";
    return VCDParser::parser::make_TOK_KW_DUMPALL(loc);
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 308 "./src/VCDScanner.l"
{
    BEGIN(IN_VAL_CHANGES);
    //std::cout << yytext << ", ";
    return VCDParser::parser::make_TOK_KW_DUMPOFF(loc);
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 314 "./src/VCDScanner.l"
{
    BEGIN(IN_VAL_CHANGES);
    //std::cout << yytext << ", ";
    return VCDParser::parser::make_TOK_KW_DUMPON(loc);
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 320 "./src/VCDScanner.l"
{
    BEGIN(IN_VAL_CHANGES);
    //std::cout << yytext << ", ";
    return VCDParser::parser::make_TOK_KW_DUMPVARS(loc);
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 326 "./src/VCDScanner.l"
{
    //std::cout << yytext << ", ";
    BEGIN(IN_VAL_IDCODE);

    VCDBit val;

    switch(yytext[0]) {
        case '0':
            val = VCD_0;
            break;
        case '1':
            val = VCD_1;
            break;
        case 'x':
        case 'X':
            val = VCD_X;
            break;
        case 'z':
        case 'Z':
            val = VCD_Z;
            break;
        default:
            val = VCD_X;
            break;
    }

    return VCDParser::parser::make_TOK_VALUE(val, loc);
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 355 "./src/VCDScanner.l"
{
    //std::cout << yytext << ", ";
    BEGIN(IN_VAL_IDCODE);
    return VCDParser::parser::make_TOK_BIN_NUM(std::string(yytext), loc);
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 361 "./src/VCDScanner.l"
{
    //std::cout << yytext << ", ";
    BEGIN(IN_VAL_IDCODE);
    return VCDParser::parser::make_TOK_REAL_NUM(std::string(yytext), loc);
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 367 "./src/VCDScanner.l"
{
    //std::cout << yytext << std::endl;
    BEGIN(INITIAL);
    return VCDParser::parser::make_TOK_IDENTIFIER(std::string(yytext),loc);
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 373 "./src/VCDScanner.l"
{loc.columns();}
	YY_BREAK
case 58:
/* rule 58 can match eol */
YY_RULE_SETUP
#line 374 "./src/VCDScanner.l"
{loc.lines();}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 375 "./src/VCDScanner.l"
{loc.lines();}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(IN_COMMENT):
case YY_STATE_EOF(IN_DATE):
case YY_STATE_EOF(IN_VERSION):
case YY_STATE_EOF(IN_TIMESCALE):
case YY_STATE_EOF(IN_SCOPE):
case YY_STATE_EOF(IN_VAR):
case YY_STATE_EOF(IN_VAR_PID):
case YY_STATE_EOF(IN_VAR_PSIZE):
case YY_STATE_EOF(IN_VAR_RNG):
case YY_STATE_EOF(IN_SIMTIME):
case YY_STATE_EOF(IN_VAL_CHANGES):
case YY_STATE_EOF(IN_VAL_IDCODE):
#line 378 "./src/VCDScanner.l"
{
    return VCDParser::parser::make_END(loc);
}
	YY_BREAK
case 60:
/* rule 60 can match eol */
YY_RULE_SETUP
#line 382 "./src/VCDScanner.l"
{
    // DO nothing!
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 386 "./src/VCDScanner.l"
ECHO;
	YY_BREAK
#line 1890 "./src/VCDScanner.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
/* %if-c-only */
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
/* %endif */
/* %if-c++-only */
/* %endif */
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
/* %% [14.0] code to do back-up for compressed tables and set up yy_cp goes here */
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */
/* %ok-for-header */

/* %if-c++-only */
/* %not-for-header */
/* %ok-for-header */

/* %endif */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
/* %if-c-only */
static int yy_get_next_buffer (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

/* %if-c-only */
/* %not-for-header */
    static yy_state_type yy_get_previous_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
/* %% [15.0] code to get the start state into yy_current_state goes here */
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
/* %% [16.0] code to find the next state goes here */
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 243 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
/* %if-c-only */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	int yy_is_jam;
    /* %% [17.0] code to find the next state, and perhaps do backing up, goes here */
	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 243 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 242);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT
/* %if-c-only */

/* %endif */
#endif

/* %if-c-only */
#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

/* %endif */
/* %if-c++-only */
/* %endif */
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

/* %% [19.0] update BOL and yylineno */

	return c;
}
/* %if-c-only */
#endif	/* ifndef YY_NO_INPUT */
/* %endif */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
/* %if-c-only */
    void yyrestart  (FILE * input_file )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/* %if-c++-only */
/* %endif */

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
/* %if-c-only */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

/* %if-c-only */
static void yy_load_buffer_state  (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
/* %if-c-only */
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
/* %endif */
/* %if-c++-only */
/* %endif */
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
/* %if-c-only */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/* %if-c++-only */
/* %endif */

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
/* %if-c-only */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
/* %if-c-only */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )
/* %endif */
/* %if-c++-only */
/* %endif */

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

/* %if-c-only */
	b->yy_input_file = file;
/* %endif */
/* %if-c++-only */
/* %endif */
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

/* %if-c-only */

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
/* %endif */
/* %if-c++-only */
/* %endif */
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
/* %if-c-only */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/* %if-c-or-c++ */
/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
/* %if-c-only */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}
/* %endif */

/* %if-c-or-c++ */
/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
/* %if-c-only */
void yypop_buffer_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}
/* %endif */

/* %if-c-or-c++ */
/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
/* %if-c-only */
static void yyensure_buffer_stack (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}
/* %endif */

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

/* %if-c-only */
static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}
/* %endif */
/* %if-c++-only */
/* %endif */

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/* %if-c-only */
/* %if-reentrant */
/* %endif */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/* %if-reentrant */
/* %endif */

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

/* %endif */

/* %if-reentrant */
/* %if-bison-bridge */
/* %endif */
/* %endif if-c-only */

/* %if-c-only */
static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}
/* %endif */

/* %if-c-only SNIP! this currently causes conflicts with the c++ scanner */
/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

/* %if-reentrant */
/* %endif */
    return 0;
}
/* %endif */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

/* %if-tables-serialization definitions */
/* %define-yytables   The name for this specific scanner's tables. */
#define YYTABLES_NAME "yytables"
/* %endif */

/* %ok-for-header */

#line 386 "./src/VCDScanner.l"


void VCDFileParser::scan_begin() {
    yy_flex_debug = trace_scanning;
    if(filepath.empty() || filepath == "-") {
        yyin = stdin;
    }
    else if(!(yyin = fopen(filepath.c_str(), "r"))) {
        error("Cannot open "+filepath+": "+strerror(errno));
        exit(EXIT_FAILURE);
    }
}

void VCDFileParser::scan_end() {
    fclose(yyin);
    yypop_buffer_state();
}

